export const CHANGE_COLOR = 'CHANGE_COLOR';
export const CHANGE_TIME_FORMAT = 'CHANGE_TIME_FORMAT';
export const CHANGE_ON_ENTER_PROP = 'CHANGE_ON_ENTER_PROP';
export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const RESET_DEFAULT = 'RESET_DEFAULT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_CURRENT_MESSAGE = 'SET_CURRENT_MESSAGE';